const data = {
    products: [
        {
            _id: '1',
            name: 'MI Slim T-Shirt',
            category: 'T-shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock:10,
            brand: 'MI',
            rating: '4.5',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'CSK Slim T-Shirt',
            category: 'T-shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock:20,
            brand: 'CSK',
            rating: '4.0',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'RCB Slim T-Shirt',
            category: 'T-shirts',
            image: '/images/p3.jpeg',
            price: 130,
            countInStock:0,
            brand: 'RCB',
            rating: '4.5',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'DD Slim T-Shirt',
            category: 'T-shirts',
            image: '/images/p4.jpeg',
            price: 140,
            countInStock:14,
            brand: 'DD',
            rating: '4.7',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'KKR Slim T-Shirt',
            category: 'T-shirts',
            image: '/images/p5.jpeg',
            price: 150,
            countInStock:12,
            brand: 'KKR',
            rating: '4.5',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'RR Slim T-Shirt',
            category: 'T-shirts',
            image: '/images/p6.jpeg',
            price: 160,
            countInStock:11,
            brand: 'RR',
            rating: '4.5',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'CSK Slim T-Shirt',
            category: 'T-shirts',
            image: '/images/p7.jpg',
            price: 170,
            countInStock:12,
            brand: 'CSK',
            rating: '4.5',
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'DD Slim T-Shirt',
            category: 'T-shirts',
            image: '/images/p8.jpeg',
            price: 200,
            countInStock:11,
            brand: 'DD',
            rating: '4.5',
            numReviews: 10,
            description: 'high quality product',
        },

    ],
};

export default data;